name: Publish to GitHub Packages Apache Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Download and Setup Trivy
      run: |
        latest_url="https://github.com/aquasecurity/trivy/releases/latest/"
        release=$(curl $latest_url -s -L -I -o /dev/null -w '%{url_effective}' | awk -F'/' '{print $NF}')
        release_num=${release/#v/}
        url="https://github.com/aquasecurity/trivy/releases/download/${release}/trivy_${release_num}_Linux-64bit.tar.gz"
        
        curl -L -o trivy.tar.gz $url
        mkdir -p src/main/resources/trivy
        tar -zxvf trivy.tar.gz -C src/main/resources/trivy

    - name: Download Trivy Vulnerability Databases
      run: |
        cd src/main/resources/trivy
        
        # Download vulnerability databases
        ./trivy image --cache-dir . --download-db-only --db-repository public.ecr.aws/aquasecurity/trivy-db
        ./trivy image --cache-dir . --download-java-db-only  --db-repository public.ecr.aws/aquasecurity/trivy-db

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
