name: Publish to GitHub Packages Apache Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Download and Setup Syft
      run: |
        latest_url="https://github.com/anchore/syft/releases/latest/"
        release=$(curl $latest_url -s -L -I -o /dev/null -w '%{url_effective}' | awk -F'/' '{print $NF}')
        release_num=${release/#v/}
        url="https://github.com/anchore/syft/releases/download/${release}/syft_${release_num}_linux_amd64.tar.gz"
        
        curl -L -o syft.tar.gz $url
        mkdir -p src/main/resources/syft
        tar -zxvf syft.tar.gz -C src/main/resources/syft

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Publish to GitHub Packages Apache Maven
      run: mvn versions:set -DnewVersion=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)-${{ github.sha }} && mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
